# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: KeyboardKit
description: >-
  KeyboardKit helps you create custom keyboards for iOS and iPadOS, using Swift and SwiftUI. 

url: https://keyboardkit.com
email: info@keyboardkit.com

is_lib: 1

copyright_year: 2016-2026
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: keyboardkit.bsky.social
github_username: KeyboardKit
mastodon_username: keyboardkit@techhub.social
twitter_username: keyboardkitsdk

assets: /assets/
header_image: /assets/icon/icon-header.png
header_image_type: icon

locales:
  count:      75
  flags:      🇺🇸 🇦🇱 🇦🇪 🇦🇲 🇦🇿 🇧🇾 🇧🇩 🇧🇬 🇦🇩 🏳️ 🏳️ 🇭🇷 🇨🇿 🇩🇰 🇳🇱 🇧🇪 🇦🇺 🇨🇦 🇬🇧 🇺🇸 🇪🇪 🇫🇴 🇵🇭 🇫🇮 🇫🇷 🇨🇦 🇧🇪 🇨🇭 🇬🇪 🇩🇪 🇦🇹 🇨🇭 🇬🇷 🇺🇸 🇮🇱 🇭🇺 🇮🇸 🏳️ 🇮🇩 🇮🇪 🇮🇹 🇰🇿 🇹🇯 🇹🇯 🇹🇯 🇱🇻 🇱🇹 🇲🇰 🇲🇾 🇲🇹 🇲🇳 🏳️ 🇳🇴 🇳🇴 🇮🇷 🇵🇱 🇵🇹 🇧🇷 🇷🇴 🇷🇺 🇷🇸 🇷🇸 🇹🇯 🇸🇰 🇸🇮 🇪🇸 🇦🇷 🇲🇽 🇸🇪 🇰🇪 🇹🇷 🇺🇦 🇺🇿 🇻🇳 🏴󠁧󠁢󠁷󠁬󠁳󠁿

urls:
  email:      mailto:info@keyboardkit.com
  email-business-license: mailto:info@keyboardkit.com?subject=Business%License
  email-custom-terms: mailto:info@keyboardkit.com?subject=Custom%20Terms
  rss:        https://keyboardkit.com/feed.xml

  appstore:   https://itunes.apple.com/app/keyboardkit/id1568444977
  blog:       /blog
  bluesky:    https://bsky.app/profile/keyboardkit.bsky.social
  docs:       https://docs.keyboardkit.com
  github:     https://github.com/KeyboardKit/KeyboardKit
  gumroad:    https://kankoda.gumroad.com/l/keyboardkitpro
  mastodon:   https://techhub.social/@keyboardkit
  newsletter: https://kankoda.gumroad.com/subscribe
  pricing:    /pricing
  reddit:     https://www.reddit.com/r/KeyboardKit
  twitter:    https://twitter.com/keyboardkitsdk

  swift:      https://www.swift.org
  swiftui:    https://developer.apple.com/xcode/swiftui/

google-analytics:
  measurement-id: G-XJ0HPZDSM3

# header:
#  banner:
#    text: 👑 Cyber Monday Discount - Save 50% on KeyboardKit Pro! 👑
#    url:  /blog/2024/12/02/cyber-monday

header:
  pages:
    - pages/home.md
    - pages/features.md
    - pages/blog.md
    - pages/pricing.md

footer:
  sitemap:
    - index.html
    - pages/about/about.md
    - pages/features.md
    - pages/pricing.md
    - pages/pro/business-licenses.md
    - pages/app/app.md
    - pages/case-studies.md
    - pages/documentation.md

collections_dir: collections

collections:
  case-studies:
    output: true
    permalink: /case-studies/:name
  features:
    output: true
    permalink: /features/:name
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include: [".well-known"]

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: page
      image: /assets/headers/keyboardkit.jpg
      page-class: glass-background bg1
  -
    scope:
      type: "case-studies"
    values:
      layout: case-study
  -
    scope:
      type: "features"
    values:
      layout: feature
      page-class: glass-background bg1
      assets: /assets/features/
  -
    scope:
      type: "posts"
    values:
      layout: post
      author: danielsaidi
      image:  /assets/headers/blog.jpg
      page-class: glass-background bg1

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/